### ISSUE TITLE
TemplateDoesNotExist at /admin/lineup/menuitem/

### ISSUE THREAD

**Issue by IDiston-VA** [abidibo/django-lineup#3]
* Django Lineup version:  0.3.0
* Django version: 3.2.8
* Python version: 3.9.5
* Operating System: Win10

### Description

Followed instructions and used example json content from documentation.  Menu shows on webpage, but when attempting to access the Admin page '**Menu**' by clicking on '**Menu items**' I get **TemplateDoesNotExist at /admin/lineup/menuitem/**.  **Change** also fails, however, **Add** works.

If I try and Add a Menu item, i can populate the fields, but when I click Save I get '**TemplateDoesNotExist at /admin/lineup/menuitem/'**

**Error**

Request Method: GET
Request URL: http://127.0.0.1:8000/admin/lineup/menuitem/

Django Version: 3.2.8
Python Version: 3.9.5
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'users.apps.UsersConfig',
 'pages.apps.PagesConfig',
 'material',
 'lineup.apps.LineupConfig']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Template loader postmortem
Django tried loading these templates, in this order:

Using engine django:
    * django.template.loaders.filesystem.Loader: /mnt/c/Code/news/templates/admin/mptt_change_list.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /home/ian/.local/share/virtualenvs/news-2nUCkXD_/lib/python3.9/site-packages/django/contrib/admin/templates/admin/mptt_change_list.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /home/ian/.local/share/virtualenvs/news-2nUCkXD_/lib/python3.9/site-packages/django/contrib/auth/templates/admin/mptt_change_list.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /home/ian/.local/share/virtualenvs/news-2nUCkXD_/lib/python3.9/site-packages/material/templates/admin/mptt_change_list.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /home/ian/.local/share/virtualenvs/news-2nUCkXD_/lib/python3.9/site-packages/lineup/templates/admin/mptt_change_list.html (Source does not exist)

Traceback (most recent call last):
  File "/home/ian/.local/share/virtualenvs/news-2nUCkXD_/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ian/.local/share/virtualenvs/news-2nUCkXD_/lib/python3.9/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/home/ian/.local/share/virtualenvs/news-2nUCkXD_/lib/python3.9/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/ian/.local/share/virtualenvs/news-2nUCkXD_/lib/python3.9/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/ian/.local/share/virtualenvs/news-2nUCkXD_/lib/python3.9/site-packages/django/template/response.py", line 65, in resolve_template
    return get_template(template, using=self.using)
  File "/home/ian/.local/share/virtualenvs/news-2nUCkXD_/lib/python3.9/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)

Exception Type: TemplateDoesNotExist at /admin/lineup/menuitem/
Exception Value: admin/mptt_change_list.html

**Comment by def324** [comment]
Adding 'mptt' to INSTALLED_APPS was what fixed it for me.
